export const SELECTED_PATH = 'SELECTED_PATH';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const REGISTER_SYSTEM = 'REGISTER_SYSTEM';
export const REGISTER_EVENT = 'REGISTER_EVENT';
export const REGISTER_RULE = 'REGISTER_RULE';
